#goal
TargetColour target_colour      # Target colour label and HSV thresholds
---
#result
bool response_signal            # A boolean response to indicate that the action has been performed
---
#feedback
uint32 target_pixel_count       # Number of target colour pixels in robot's vision
float32 displacement            # Robot displacement from starting position
