#goal
TargetColour target_colour         # Target colour label and HSV thresholds
---
#result
float32 total_distance_travelled   # Total distance travelled during the action (meters)
float32 closest_object_distance    # LaserScan distance to the closest detected obstacle (meters) 
float32 closest_object_angle       # The LaserScan angle of the closest detected obstacle (degrees)
---
#feedback
float32 current_distance_travelled # Distance travelled so far during the action (meters)
